# Generated by Django 5.0.7 on 2024-07-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=20)),
                ('hospital_type', models.CharField(max_length=20)),
                ('symptom_type', models.CharField(max_length=20)),
                ('symptom_etc', models.CharField(max_length=20)),
                ('illness_etc', models.CharField(max_length=20)),
                ('medicine_etc', models.CharField(max_length=20)),
                ('etc', models.CharField(max_length=20)),
                ('ins_req1', models.CharField(max_length=20)),
                ('ins_req2', models.CharField(max_length=20)),
                ('hospital_fee', models.CharField(max_length=20)),
                ('document', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=20)),
                ('hospital_category', models.CharField(max_length=20)),
                ('hospital_tel', models.IntegerField()),
                ('hospital_ratings', models.CharField(max_length=20)),
                ('hospital_open', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
