# Generated by Django 5.0.7 on 2024-07-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediinfo',
            name='allergy',
            field=models.CharField(default='알레르기 없음', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediinfo',
            name='diagnosis',
            field=models.CharField(default='근 n개월 이내 없음', max_length=20),
        ),
    ]
