# Generated by Django 5.0.7 on 2024-07-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0002_alter_mediinfo_allergy_alter_mediinfo_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediinfo',
            name='medicine',
            field=models.CharField(default='복용하는 약 없음', max_length=20),
        ),
    ]
