# Generated by Django 5.0.7 on 2024-07-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0002_alter_assist_hospital_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='facility',
            field=models.CharField(choices=[('약국', '약국'), ('병원', '병원')], default='병원', max_length=20),
        ),
    ]
