# Generated by Django 5.0.7 on 2024-07-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0002_script'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insurance',
        ),
    ]
