# Generated by Django 5.0.7 on 2024-07-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0003_alter_assist_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='assist',
        ),
        migrations.AddField(
            model_name='assist',
            name='recommended_hospitals',
            field=models.ManyToManyField(blank=True, related_name='recommended_by_assists', to='medicarrier.hospital'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_tel',
            field=models.CharField(max_length=15),
        ),
    ]
