# Generated by Django 5.0.7 on 2024-07-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0003_delete_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_longitude',
            field=models.FloatField(default=0),
        ),
    ]
