# Generated by Django 5.0.7 on 2024-07-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0003_mediinfo_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='medicard',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medicarrier.medicard'),
        ),
    ]
