# Generated by Django 5.0.3 on 2024-07-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0004_hospital_hospital_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_distance', models.CharField(default='', max_length=20)),
                ('pharmacy_name', models.CharField(max_length=20)),
                ('pharmacy_category', models.CharField(max_length=20)),
                ('pharmacy_tel', models.CharField(max_length=15)),
                ('pharmacy_ratings', models.CharField(max_length=20)),
                ('pharmacy_open', models.BooleanField()),
                ('pharmacy_latitude', models.FloatField(default=0)),
                ('pharmacy_longitude', models.FloatField(default=0)),
            ],
        ),
    ]
