# Generated by Django 5.0.7 on 2024-07-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0005_alter_assist_facility_alter_assist_hospital_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assist',
            name='symptom_freq',
            field=models.CharField(choices=[('지속적', '지속적'), ('간헐적', '간헐적'), ('특정 시간에만', '특정 시간에만')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='assist',
            name='symptom_start',
            field=models.CharField(choices=[('오늘', '오늘'), ('1일 전', '1일 전'), ('2-3일 전', '2-3일 전'), ('일주일 전', '일주일 전'), ('일주일 이상', '일주일 이상')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='assist',
            name='etc',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='assist',
            name='illness_etc',
            field=models.CharField(default='없', max_length=20),
        ),
        migrations.AlterField(
            model_name='assist',
            name='ins_req1',
            field=models.CharField(choices=[('질병', '질병'), ('상해', '상해'), ('특정 시간에만', '특정 시간에만')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='assist',
            name='ins_req2',
            field=models.CharField(choices=[('입원', '입원'), ('통원', '통원'), ('사망', '사망'), ('후유장애', '후유장애'), ('수술', '수술')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='assist',
            name='medicine_etc',
            field=models.CharField(default='없습', max_length=20),
        ),
        migrations.AlterField(
            model_name='assist',
            name='symptom_etc',
            field=models.CharField(default='', max_length=20),
        ),
    ]
