# Generated by Django 5.0.7 on 2024-07-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0005_remove_assist_recommended_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='assist',
            name='recommended_hospitals',
            field=models.ManyToManyField(blank=True, related_name='recommended_by_assists', to='medicarrier.hospital'),
        ),
    ]
