# Generated by Django 5.0.7 on 2024-07-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0006_assist_symptom_freq_assist_symptom_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_distance',
            field=models.CharField(default='', max_length=20),
        ),
    ]
