# Generated by Django 5.0.7 on 2024-07-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0006_assist_recommended_hospitals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assist',
            name='recommended_hospitals',
        ),
    ]
