# Generated by Django 5.0.7 on 2024-07-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0007_hospital_hospital_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='hospital_fee',
            field=models.CharField(choices=[('3만원 미만', '3만원 미만'), ('3만원 이상 ~ 10만원 미만', '3만원 이상 ~ 10만원 미만'), ('10만원 이상', '10만원 이상')], default='', max_length=20),
        ),
    ]
