# Generated by Django 5.0.7 on 2024-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0007_alter_medicard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicard',
            name='country',
            field=models.CharField(max_length=20),
        ),
    ]
