# Generated by Django 5.0.3 on 2024-07-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0005_pharmacy'),
        ('medicarrier', '0007_remove_assist_recommended_hospitals'),
    ]

    operations = [
    ]
