# Generated by Django 5.0.3 on 2024-07-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0008_alter_medicard_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=20)),
                ('insurance_call', models.CharField(max_length=20)),
                ('insurance_type', models.CharField(choices=[('실속형', '실속형'), ('표준형', '표준형'), ('고급형', '고급형')], max_length=10)),
            ],
        ),
    ]
