# Generated by Django 5.0.7 on 2024-07-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0008_alter_assist_hospital_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='document',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assist',
            name='etc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assist',
            name='symptom_etc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
