# Generated by Django 5.0.3 on 2024-07-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0008_merge_20240729_1707'),
        ('medicarrier', '0008_merge_20240729_1708'),
    ]

    operations = [
    ]
