# Generated by Django 5.0.7 on 2024-07-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0009_alter_basicinfo_bloodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tripInssurance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
