# Generated by Django 5.0.7 on 2024-07-28 04:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0009_script'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicard',
            unique_together={('user', 'country')},
        ),
    ]
