# Generated by Django 5.0.3 on 2024-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0009_merge_20240729_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='insuranceType',
            field=models.CharField(default='실속형', max_length=20),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='bloodtype',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20),
        ),
    ]
