# Generated by Django 5.0.7 on 2024-07-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0009_alter_assist_document_alter_assist_etc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assist',
            name='document',
        ),
    ]
