# Generated by Django 5.0.7 on 2024-07-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0010_remove_assist_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='assist',
            name='document',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
