# Generated by Django 5.0.7 on 2024-07-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0010_alter_medicard_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicard',
            unique_together=set(),
        ),
    ]
