# Generated by Django 5.0.7 on 2024-07-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0010_trip_tripinssurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='tripInssurance',
        ),
    ]
