# Generated by Django 5.0.3 on 2024-07-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0011_alter_basicinfo_bloodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='bloodtype',
            field=models.CharField(choices=[('RH+ A', 'RH+ A'), ('RH- A', 'RH- A'), ('RH+ B', 'RH+ B'), ('RH- B', 'RH- B'), ('RH+ O', 'RH+ O'), ('RH- O', 'RH- O'), ('RH+ AB', 'RH+ AB'), ('RH- AB', 'RH- AB')], max_length=20),
        ),
    ]
