# Generated by Django 5.0.7 on 2024-07-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0011_assist_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='document',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assist',
            name='etc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assist',
            name='symptom_etc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
