# Generated by Django 5.0.7 on 2024-07-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0012_alter_assist_document_alter_assist_etc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='ins_req1',
            field=models.CharField(choices=[('질병', '질병'), ('상해', '상해')], default='', max_length=20),
        ),
    ]
