# Generated by Django 5.0.7 on 2024-07-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0011_remove_trip_tripinssurance'),
        ('medicarrier', '0012_alter_basicinfo_bloodtype'),
    ]

    operations = [
    ]
