# Generated by Django 5.0.7 on 2024-08-01 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0013_merge_20240731_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='assist',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
