# Generated by Django 5.0.7 on 2024-07-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0013_alter_assist_ins_req1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='ins_req2',
            field=models.CharField(choices=[('입원', '입원'), ('통원', '통원'), ('사망', '사망'), ('후유장해', '후유장해'), ('수술', '수술')], default='', max_length=20),
        ),
    ]
