# Generated by Django 5.0.7 on 2024-07-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0014_alter_assist_ins_req2'),
    ]

    operations = [
        migrations.AddField(
            model_name='assist',
            name='full_inheritance',
            field=models.CharField(choices=[('수익자 미지정 시', '수익자 미지정 시'), ('1인의 상속인의 전액 수령을 원하는 경우', '1인의 상속인의 전액 수령을 원하는 경우')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assist',
            name='document',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
