# Generated by Django 5.0.7 on 2024-08-03 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0014_assist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trip',
            name='insuranceType',
            field=models.CharField(default='없음', max_length=20),
        ),
    ]
