# Generated by Django 5.0.7 on 2024-07-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0015_assist_full_inheritance_alter_assist_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='ins_req2',
            field=models.CharField(choices=[('입원', '입원'), ('통원', '통원'), ('사망', '사망'), ('후유장해', '후유장해'), ('수술', '수술'), ('진단', '진단')], default='', max_length=20),
        ),
    ]
