# Generated by Django 5.0.7 on 2024-07-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0016_alter_assist_ins_req2'),
    ]

    operations = [
        migrations.AddField(
            model_name='assist',
            name='disease_detail',
            field=models.CharField(choices=[('암', '암'), ('뇌질환', '뇌질환'), ('심질환', '심질환'), ('기타', '기타')], default='', max_length=20),
        ),
    ]
