# Generated by Django 5.0.7 on 2024-07-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0018_alter_assist_ins_req2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assist',
            name='full_inheritance',
        ),
    ]
