# Generated by Django 5.0.7 on 2024-07-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicarrier', '0019_remove_assist_full_inheritance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='document',
            field=models.TextField(blank=True, null=True),
        ),
    ]
